export const ChapterData = [
  {
    id: 1,
    chapternumber: "১",
    name: "ওহীর সূচনা অধ্যায়",
    range: "১ - ৭",
  },
  {
    id: 2,
    chapternumber: "২",
    name: "দ্বিতীয় অধ্যায়",
    range: "২ - ৮",
  },
  {
    id: 3,
    chapternumber: "৩",
    name: "তৃতীয় অধ্যায়",
    range: "৩ - ৯",
  },
  {
    id: 4,
    chapternumber: "৪",
    name: "চতুর্থ অধ্যায়",
    range: "৪ - ১০",
  },
  {
    id: 5,
    chapternumber: "৫",
    name: "পঞ্চম অধ্যায়",
    range: "৫ - ১১",
  },
  {
    id: 6,
    chapternumber: "৬",
    name: "ষষ্ঠ অধ্যায়",
    range: "৬ - ১২",
  },
  {
    id: 7,
    chapternumber: "৭",
    name: "সপ্তম অধ্যায়",
    range: "৭ - ১৩",
  },
  {
    id: 8,
    chapternumber: "৮",
    name: "অষ্টম অধ্যায়",
    range: "৮ - ১৪",
  },
  {
    id: 9,
    chapternumber: "৯",
    name: "নবম অধ্যায়",
    range: "৯ - ১৫",
  },
  {
    id: 10,
    chapternumber: "১০",
    name: "দশম অধ্যায়",
    range: "১০ - ১৬",
  },
  {
    id: 11,
    chapternumber: "১১",
    name: "এগারোম অধ্যায়",
    range: "১১ - ১৭",
  },
  {
    id: 12,
    chapternumber: "১২",
    name: "বারোম অধ্যায়",
    range: "১২ - ১৮",
  },
  {
    id: 13,
    chapternumber: "১৩",
    name: "তেরোম অধ্যায়",
    range: "১৩ - ১৯",
  },
  {
    id: 14,
    chapternumber: "১৪",
    name: "চৌদ্দোম অধ্যায়",
    range: "১৪ - ২০",
  },
  {
    id: 15,
    chapternumber: "১৫",
    name: "পনেরোম অধ্যায়",
    range: "১৫ - ২১",
  },
  {
    id: 16,
    chapternumber: "১৬",
    name: "ষোলোম অধ্যায়",
    range: "১৬ - ২২",
  },
  {
    id: 17,
    chapternumber: "১৭",
    name: "সতেরোম অধ্যায়",
    range: "১৭ - ২৩",
  },
  {
    id: 18,
    chapternumber: "১৮",
    name: "আঠারোম অধ্যায়",
    range: "১৮ - ২৪",
  },
  {
    id: 19,
    chapternumber: "১৯",
    name: "উনিশওম অধ্যায়",
    range: "১৯ - ২৫",
  },
  {
    id: 20,
    chapternumber: "২০",
    name: "বিশওম অধ্যায়",
    range: "২০ - ২৬",
  },
];
